apiVersion: apps/v1
kind: Deployment
metadata:
  name: lembretes-deployment
spec:
  #quantas cópias
  replicas: 1
  selector:
    matchLabels:
      app: lembretes
  template:
    metadata:
      labels:
        app: lembretes
    spec:
      containers:
        - name: lembretes
          image: nat250/ecm516-20232-lembretes
          # resources:
          #   limits:
          #     memory: 256Mi
          #     cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: lembretes-clusterip-service
spec:
  selector:
    app: lembretes
  type: ClusterIP
  ports:
    - name: lembretes
      protocol: TCP
      port: 4000
      targetPort: 4000